### ISSUE TITLE
Fix width

### ISSUE THREAD

**Issue by lprhodes** [redpandatronicsuk/arty-charty#3]
Hi - how do you go about specifying a fixed width for the chart. I'm working with the spline charts and at the moment the width it dynamic based on the data points but ideally it would be a fixed width and the points would spread accordingly.

**Comment by redpandatronicsuk** [comment]
Sorry for getting back so late, completely missed this. At the moment graphs are always full width. I'll add a width parameter in the next update. I've been busy with other projects lately, I hope I can get that update out in the next few days.

**Comment by redpandatronicsuk** [comment]
I added a width parameter to the ArtyCharty component now. If you update, make sure you read the new installation instructions. We use react-native-svg now instead of ART, so make sure you have react-native-svg installed.

**Comment by redpandatronicsuk** [comment]
I suppose it works and will close the issue now.
